from reportlab.lib.pagesizes import A4
from reportlab.lib import colors
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.platypus import SimpleDocTemplate, Table, TableStyle, Paragraph, Spacer, Image
from reportlab.lib.units import inch
from io import BytesIO
import datetime

class PDFGenerator:
    def __init__(self):
        self.styles = getSampleStyleSheet()
        self.header_style = ParagraphStyle(
            'HeaderStyle',
            parent=self.styles['Heading1'],
            fontSize=24,
            textColor=colors.HexColor("#1e3a8a"),  # Blue-900 equivalent
            alignment=1, # Center
            spaceAfter=12
        )
        self.subheader_style = ParagraphStyle(
            'SubHeaderStyle',
            parent=self.styles['Heading2'],
            fontSize=14,
            textColor=colors.HexColor("#d97706"),  # Amber-600 equivalent
            alignment=1, # Center
            spaceAfter=20
        )
        self.info_style = self.styles['Normal']
        self.label_style = ParagraphStyle(
            'LabelStyle',
            parent=self.styles['Normal'],
            fontSize=10,
            textColor=colors.grey,
            textTransform='uppercase'
        )

    def generate_receipt(self, transaction, user_profile):
        buffer = BytesIO()
        doc = SimpleDocTemplate(buffer, pagesize=A4, rightMargin=72, leftMargin=72, topMargin=72, bottomMargin=18)
        elements = []

        # Logo/Header
        elements.append(Paragraph("BLUE-GOLD", self.header_style))
        elements.append(Paragraph("PREMIUM INVESTMENTS", self.subheader_style))
        elements.append(Spacer(1, 0.5 * inch))

        elements.append(Paragraph("TRANSACTION RECEIPT", self.styles['Heading3']))
        elements.append(Spacer(1, 0.2 * inch))

        # Amount Box
        amount = float(transaction.get('amount', 0))
        tx_type = transaction.get('transaction_type', '').lower()
        amount_color = colors.red if tx_type == 'withdrawal' else colors.green
        prefix = "-" if tx_type == 'withdrawal' else "+"
        
        amount_text = f"{prefix}N {amount:,.2f}"
        elements.append(Paragraph("Amount Transacted", self.label_style))
        elements.append(Paragraph(f"<b><font size='36' color='{amount_color}'>{amount_text}</font></b>", self.styles['Normal']))
        elements.append(Spacer(1, 0.3 * inch))

        # Transaction Details Table
        data = [
            ["Status", transaction.get('status', 'N/A').upper()],
            ["Merchant", "Blue-Gold Premium Investments"],
            ["Date/Time", transaction.get('created_at', 'N/A')],
            ["Transaction Type", transaction.get('transaction_type', 'N/A').capitalize()],
            ["Reference Number", transaction.get('transaction_id', 'N/A')],
            ["Customer Name", f"{user_profile.get('first_name', '')} {user_profile.get('surname', '')}"],
            ["Account Number", user_profile.get('account_number', 'N/A')],
            ["Description", transaction.get('description', 'N/A')]
        ]

        t = Table(data, colWidths=[2 * inch, 3.5 * inch])
        t.setStyle(TableStyle([
            ('TEXTCOLOR', (0, 0), (-1, -1), colors.black),
            ('INNERGRID', (0, 0), (-1, -1), 0.25, colors.grey),
            ('BOX', (0, 0), (-1, -1), 0.25, colors.grey),
            ('FONTNAME', (0, 0), (0, -1), 'Helvetica-Bold'),
            ('VALIGN', (0, 0), (-1, -1), 'MIDDLE'),
            ('BOTTOMPADDING', (0, 0), (-1, -1), 8),
            ('TOPPADDING', (0, 0), (-1, -1), 8),
        ]))
        elements.append(t)

        elements.append(Spacer(1, 1 * inch))
        elements.append(Paragraph("This is an automated receipt generated by Blue-Gold System.", self.styles['Italic']))
        elements.append(Paragraph("No signature is required for validity.", self.styles['Italic']))

        doc.build(elements)
        buffer.seek(0)
        return buffer

    def generate_history_report(self, transactions, user_profile):
        buffer = BytesIO()
        doc = SimpleDocTemplate(buffer, pagesize=A4, rightMargin=30, leftMargin=30, topMargin=50, bottomMargin=30)
        elements = []

        # Logo/Header
        elements.append(Paragraph("BLUE-GOLD", self.header_style))
        elements.append(Paragraph("TRANSACTION HISTORY REPORT", self.subheader_style))
        elements.append(Spacer(1, 0.2 * inch))

        # User Profile Box
        profile_data = [
            ["Account Holder", f"{user_profile.get('first_name', '')} {user_profile.get('surname', '')}"],
            ["Email", user_profile.get('email', 'N/A')],
            ["Account Number", user_profile.get('account_number', 'N/A')],
            ["Total Transactions", str(len(transactions))]
        ]
        pt = Table(profile_data, colWidths=[1.5 * inch, 4 * inch])
        pt.setStyle(TableStyle([
            ('FONTNAME', (0, 0), (0, -1), 'Helvetica-Bold'),
            ('ALIGN', (0, 0), (-1, -1), 'LEFT'),
            ('BOTTOMPADDING', (0, 0), (-1, -1), 4),
        ]))
        elements.append(pt)
        elements.append(Spacer(1, 0.4 * inch))

        # Transactions Table
        header = ["Date", "Description", "Type", "Amount", "Status"]
        data = [header]

        for tx in transactions:
            tx_type = tx.get('transaction_type', '').lower()
            amount = float(tx.get('amount', 0))
            prefix = "-" if tx_type == 'withdrawal' else "+"
            amount_text = f"{prefix}N {amount:,.2f}"
            
            row = [
                tx.get('created_at', '')[:10], # Short date
                tx.get('description', tx.get('transaction_type', '')),
                tx.get('transaction_type', '').capitalize(),
                amount_text,
                tx.get('status', 'N/A')
            ]
            data.append(row)

        # Better styling for the main table
        t = Table(data, colWidths=[0.8 * inch, 2.2 * inch, 0.8 * inch, 1.2 * inch, 0.8 * inch])
        t_style = [
            ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor("#1e3a8a")),
            ('TEXTCOLOR', (0, 0), (-1, 0), colors.whitesmoke),
            ('ALIGN', (0, 0), (-1, -1), 'LEFT'),
            ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
            ('FONTSIZE', (0, 0), (-1, 0), 10),
            ('BOTTOMPADDING', (0, 0), (-1, 0), 12),
            ('BACKGROUND', (0, 1), (-1, -1), colors.whitesmoke),
            ('GRID', (0, 0), (-1, -1), 0.5, colors.grey),
            ('FONTSIZE', (0, 1), (-1, -1), 8),
            ('VALIGN', (0, 0), (-1, -1), 'MIDDLE'),
        ]
        
        # Add red/green colors for amounts (this is tricky in TableStyle directly for specific cells)
        # We can apply it row by row but it's easier to just use colors based on type
        for idx, tx in enumerate(transactions):
            row_idx = idx + 1
            if tx.get('transaction_type', '').lower() == 'withdrawal':
                t_style.append(('TEXTCOLOR', (3, row_idx), (3, row_idx), colors.red))
            else:
                t_style.append(('TEXTCOLOR', (3, row_idx), (3, row_idx), colors.green))

        t.setStyle(TableStyle(t_style))
        elements.append(t)

        elements.append(Spacer(1, 0.5 * inch))
        footer_text = f"Generated on {datetime.datetime.now().strftime('%Y-%m-%d %H:%M:%S')} - Official Blue-Gold Investment Report"
        elements.append(Paragraph(footer_text, ParagraphStyle('Footer', alignment=1, fontSize=8, textColor=colors.grey)))

        doc.build(elements)
        buffer.seek(0)
        return buffer
